disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ashif's Portfolio"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "Logos/110x110/-3 Circle 110x110.png"
  secondaryLogo = "Logos/avatar.png"
  description = "Ashif's Portfolio"
  copyright = "&copy; 2026 Ashif C. - All rights reserved."

[params.author]
  name = "Ashif C."
  email = "ashifc99.github.io.bounce673@passfwd.com"
  image = "Logos/avatar.gif"
  imageQuality = 100
  headline = "{ Edge Developer}"
  bio = "Sono un appassionato di informatica e di tutto ci√≤ che riguarda il mondo della tecnologia."
   links = [
     { email = "mailto:hashifc99.github.io.bounce673@passfwd.com" },
     { link = "https://ashif.eu/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/AshifC99" },
     { gitlab = "https://gitlab.com/AshifC99" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
     { instagram = "https://instagram.com/_.ashif._" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
     { linkedin = "https://linkedin.com/in/ashifchowdhury" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
     { x-twitter = "https://twitter.com/__ashif" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
   ]
