baseurl = "https://ashifc99.gitlab.io/ashifc99"
title = "Ashif's Portfolio"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[pagination]
pagerSize = 20

[services]


[markup.highlight]
style = "github-dark"

[params]
  author = "Ashif Chowdhury"
  info = "{ Edge Developer }"
  description = "Ashif Chowdhury's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/Logos/avatar.gif"
  #gravatar = "ashifc99.github.io.bounce673@passfwd.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ashifc99/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/ashifc99/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/__ASHIF/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Password Generator"
  weight = 2
  url = "/password_generator.html"